CREATE TABLE IF NOT EXISTS PRICES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID BIGINT,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE_LIST BIGINT,
  PRODUCT_ID BIGINT,
  PRIORITY INT,
  PRICE DOUBLE,
  CURR VARCHAR(3)
);
